on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     target: [x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check and Compile
        uses: dtolnay/rust-toolchain@stable
        run: |
          cargo build --release --target-dir out
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: out/release/personal_website
