on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
    #   fail-fast: false
      # matrix:
    #     target: [x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: add target
        run: |
          rustup target add x86_64-unknown-linux-musl
      - name: check and compile
        run: |
          cargo test
          cargo build --release --target x86_64-unknown-linux-musl --target-dir out
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: out/release/personal_website
